### ISSUE TITLE
Non-blocking version of Acquire

### ISSUE THREAD

**Issue by ajjensen13** [jackc/puddle#10]
Would you consider adding a non-blocking version of `Acquire` to this API? Instead of blocking until a resource becomes available, the API would fail if there aren't any available and there is no headroom to construct a new resource. Perhaps it could be named `TryAcquire`, `AcquireNow`, or `AquireOrFail`.

This behavior could be approximated by supplying a context with a short lifespan, but that feels clunky. And, since the context is passed into the resource constructor, it could potentially cancel an otherwise valid resource construction.

The use case I'm designing for is a scheduler that schedules work based on what resources are available. So, it would be ideal for my application to do something else if a requested resource is unavailable.

I would be happy to submit a pull request if you have any interest in adding something like that to this library. Just figured I'd ask before replicating this elsewhere.

**Comment by jackc** [comment]
👍  on `TryAcquire`.
