### ISSUE TITLE
TryAcquire will be blocked when construct resource failed

### ISSUE THREAD

**Issue by ansoda** [jackc/puddle#14]
constructor := func(ctx context.Context) (interface{}, error) {
		return net.DialTimeout("tcp", addr, 5*time.Second)
	}

When you want to create a network connection, but the network is unavailable.
DialTimeout will be blocked 5 seconds,and TryAcquire will be blocked 5 seconds also.

**Comment by jackc** [comment]
It is behaving as documented.

>  TryAcquire is the same as Acquire except it returns ErrNotAvailable if the pool is at maximum capacity and no resources are available. 

You can use provided context to limit how long to wait. (e.g. with https://pkg.go.dev/net#Dialer.DialContext)

**Comment by ansoda** [comment]
I expected the tcp network to remain blocked for 5 seconds, but TryAquirue would return immediately for whatever reason.

**Comment by jackc** [comment]
So that would be something like always return immediately if nothing is immediately available but start a background acquire if there is room in the pool. Hopefully, the resource would be available next time around. Maybe even return different errors to distinguish between pool is empty and cannot grow and starting a background acquire.

That could be a reasonable change. But @ajjensen13 added this feature just a little over a month ago. I'd like to get their opinion if possible.

**Comment by ajjensen13** [comment]
I don't have a strong opinion either way.

Although, whether or not the constructor blocks, and for how long, is outside the control of this library. Which makes it feel out of place to code around the assumption that a constructor blocks.

I have no opposition to the proposal. But, might suggest investing a wrapper function that calls TryAcquire in a go-routine to handle this specific case

**Comment by ansoda** [comment]
The main reason is that the current resource management is synchronous. If we need to implement TryAcquire, it is non-blocking in any situation. We need to complete the creation of resources in the goroutine, and automatically create supplements if the resources are insufficient.  If there are free resources, return immediately.  If the total number of resources is zero, TryAcquire immediately returns the reason why the resource is unavailable or the last resource creation failed.

**Comment by jackc** [comment]
I created PR #15 that implements most of what we have discussed. The only thing I didn't do was separate errors for why the `TryAcquire` failed. There was some ambiguity regarding what error message would be appropriate in certain circumstances. These can be added later if necessary.

Let me know if this works for everyone.

**Comment by ansoda** [comment]
Thank you for your PR, this PR can meet my needs and it is great.  But repeatedly calling TryAcquire may cause the resources in the pool to exceed the maximum number, and we can think about how to return an error.

**Comment by jackc** [comment]
>  But repeatedly calling TryAcquire may cause the resources in the pool to exceed the maximum number,

🤦 Wow. Can't believe I missed that. I guess that's why it's helpful to have some eyes on concurrent code. Just pushed a fix that should prevent the pool from overfilling.

**Comment by ansoda** [comment]
I reviewed the code and I think there is no problem, thank you.

**Comment by ansoda** [comment]
Hello, may I ask, when can you merge the PR into the master branch?

**Comment by jackc** [comment]
Done. I wanted to wait a few days to see if anyone else wanted to comment / review and to give myself a chance to look at it with fresh eyes. It still appeared correct to me. Merges and tagged `v1.2.1`.
