### ISSUE TITLE
Call to Close() hangs

### ISSUE THREAD

**Issue by JordanP** [jackc/puddle#25]
```go
package main

import (
	"context"
	"log"
	"os/signal"
	"syscall"

	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/sync/errgroup"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	db, err := pgxpool.New(ctx, "postgresql://XXX")
	if err != nil {
		log.Panicln(err)
	}
	g, ctx := errgroup.WithContext(ctx)
	g.SetLimit(8)

	loop := func() {
		for {
			select {
			case <-ctx.Done():
				return
			default:
			}
			g.Go(func() error {
				log.Println("Going to db.Exec")
				_, err := db.Exec(ctx, "select pg_sleep(0.2);")
				return err
			})
		}
	}

	loop()
	db.Close()
}
```

When running this script with `go run main.go`, if I hit ctrl+C, the program will sometimes hang on the `db.Close()` and more especially on the `p.destructWG.Wait()` line. It's pretty reliable, though you may want to try something like 10 times (go run + ctrl+c).

I couldn't debug it more :( I am on Linux go 1.19.

Edit: I noticed that if I hit ctrl+c quite early after the program started, there's a higher chance to reproduce the deadlock.

**Comment by jackc** [comment]
I wonder if there is something specific to Linux. I tried it about 30 times on `go version go1.19.2 darwin/amd64` and was unable to reproduce the issue.

Hmm, no luck on `go version go1.19.1 linux/amd64` either.

Not really sure what else to try. OTOH, #24 will probably be merged sometime soon, so maybe it won't matter.

**Comment by JordanP** [comment]
Maybe it has to do with my PG DB being 300ms away from my laptop. 

I am going to close this one, I hope #24 will make it, but no rush,.
