### ISSUE TITLE
question: How to automatically delete outdated resources?

### ISSUE THREAD

**Issue by cyberhck** [jackc/puddle#27]
We rotate credentials on the fly, this would include credentials for AWS, databases, google cloud platform, etc.

is there a way to automatically delete the resources that were created more than a certain number of minutes ago? Or is that a bad idea? I was also thinking, we could Destroy IF the resource results in an error, but that'd mean if there's a genuine error happening, then we'd drain our pool of resources.

Do you have any recommendations on how we would go about this? :), currently, I'm using a resource, then checking if it was created more than a certain number of minutes ago, then destroying it.

**Comment by cyberhck** [comment]
Or better title would be how to recycle pooled items.

**Comment by jackc** [comment]
You can use a goroutine that occasionally calls `AcquireAllIdle()` and does a health check on them. In addition, you can wrap puddle such that checks can be performed when a resource is released.

https://github.com/jackc/pgx/tree/master/pgxpool might be a helpful example. It implements max lifetime and max idle time on top of puddle.

**Comment by cyberhck** [comment]
Thank you @jackc that helps :)
