### ISSUE TITLE
Question: are you ok if we add the possibility to resize the max pool size?

### ISSUE THREAD

**Issue by Jrmy2402** [jackc/puddle#33]
I want to know, are you open to an MR to give the possibility to resize the pool size on the fly?

If you're up for it, I can create a MR. Thanks!

**Comment by jackc** [comment]
Resizing the pool while it is in use introduces some *interesting* edge cases. For example, reducing the size of the pool to less than the amount of currently checked out resources would be tricky.

There's a lot of subtle logic in the pool. I would prefer to avoid any changes if possible. Could your use case be handled by a wrapper object?

**Comment by Jrmy2402** [comment]
Yes, we can handle it by a wrapper, but then we need to define the max pool size to the maximum size we could have and manage the size check in the wrapper, which makes Puddle less interesting.

Is it not possible to make a setter that returns an error if the pool amount of currently checked-out resources is greater than the new value, and then in the wrapper, I manage the destruction of the excess resources?

I understand your point; if it is not possible, I will implement it all in my wrapper.

**Comment by Jrmy2402** [comment]
@jackc, are you okay if I do an MR to make a setter that returns an error if the pool amount of currently checked-out resources is greater than the new value?

**Comment by jackc** [comment]
> @jackc, are you okay if I do an MR to make a setter that returns an error if the pool amount of currently checked-out resources is greater than the new value?

I suppose that would be a reasonably safe change, but I'm still not convinced that it is necessary or the best approach.

If there is an API to adjust the max size of the pool, then that implies there is some sort of wrapper or controller that has a true max size and it is monitoring something and occasionally adjusting the size of the underlying puddle `*Pool`. But that is nearly equivalent to setting `MaxSize` to whatever the true max size is and using `*Pool.Stat()`, `*Pool.AcquireAllIdle()`, and `*Resource.Destroy()` to enforce a lower soft max size.

This is the approach pgx takes with its pool. It has a periodic health check that enforces max lifetime and max idle time. The same approach could be used for a soft max size.
